// Client-safe blog utility functions
// These can be used in both server and client components

export async function generateUniqueSlug(
  title: string,
  _excludeId?: string,
): Promise<string> {
  // This is a simplified version for client-side usage
  // In production, this should call an API endpoint to ensure uniqueness

  // Convert title to slug
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

  // For client-side generation, we'll return the base slug
  // The API will handle final uniqueness checking and add numbers if needed
  return slug;
}

export function calculateReadingTime(content: string): number {
  // Average reading speed: 200 words per minute
  const wordsPerMinute = 200;
  const words = content.trim().split(/\s+/).length;
  const readingTime = Math.ceil(words / wordsPerMinute);
  return Math.max(1, readingTime); // Minimum 1 minute
}

// Client-side version that doesn't require server imports
// This generates clean slugs without timestamps - the server will handle uniqueness
export function generateUniqueSlugSync(title: string): string {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

  // Return clean slug without timestamp
  // Server will ensure uniqueness by adding numbers if needed
  return slug;
}

// Helper function to check if a slug looks auto-generated (for form logic)
export function isAutoGeneratedSlug(slug: string): boolean {
  // Check if slug ends with a timestamp pattern (old format)
  const timestampPattern = /-[a-z0-9]{8,}$/;
  return timestampPattern.test(slug);
}

// Helper function to generate slug from title with user-friendly formatting
export function generateSlugFromTitle(title: string): string {
  return title
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, "") // Remove special characters except spaces and hyphens
    .replace(/\s+/g, "-") // Replace spaces with hyphens
    .replace(/-+/g, "-") // Replace multiple hyphens with single hyphen
    .replace(/^-+|-+$/g, ""); // Remove leading/trailing hyphens
}

// Function to validate slug format in real-time
export function validateSlugFormat(slug: string): {
  isValid: boolean;
  error?: string;
} {
  if (!slug || slug.trim() === "") {
    return { isValid: true }; // Empty slug is valid (will be auto-generated)
  }

  const trimmedSlug = slug.trim();

  // Check length
  if (trimmedSlug.length > 200) {
    return { isValid: false, error: "Slug cannot exceed 200 characters" };
  }

  // Check format
  const slugRegex = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
  if (!slugRegex.test(trimmedSlug)) {
    return {
      isValid: false,
      error:
        "Slug must contain only lowercase letters, numbers, and hyphens. Cannot start or end with hyphens.",
    };
  }

  return { isValid: true };
}

// Function to clean and format a slug string
export function cleanSlug(slug: string): string {
  return slug
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, "") // Remove special characters except spaces and hyphens
    .replace(/\s+/g, "-") // Replace spaces with hyphens
    .replace(/-+/g, "-") // Replace multiple hyphens with single hyphen
    .replace(/^-+|-+$/g, ""); // Remove leading/trailing hyphens
}
